### ISSUE TITLE
Current Version branch

### ISSUE THREAD

**Issue by MSchmidt** [iaian7/mediaboxAdvanced#1]
The changelog on the website (http://iaian7.com/webcode/mediaboxAdvanced) suggests that there is a v1.4.6, however the master branch contains an old v1.3 version and the download on the website is 1.3 as well.

What happened to 1.4? Is it not publicly available?

**Comment by iaian7** [comment]
Sorry about the confusion, I haven't been able to update Git in a very long time! The website links to 1.3.4 as an "official" release, but I've been working on 1.4.x for a while now...sadly haven't had the time to finalise it yet. The bigger issue right now is that I'm unhappy with the level of complexity - would love to start from scratch and bypass all the baggage from the original Slimbox (some of the code is just a bit over my head :D), but no time right now.

For now, there's 1.3.4 on the download page, or the slightly more reliable 1.2.5 under Older Versions.

You can always check the page source code, which will link to the latest working version (currently 1.4.6). :D
