### ISSUE TITLE
ClickBlock Errors

### ISSUE THREAD

**Issue by nicekiwi** [iaian7/mediaboxAdvanced#5]
Line 248, 

```
if (options.clickBlock && this.toString().match(/\.gif|\.jpg|\.jpeg|\.png/i)) e.stop();
```

should be:

```
if (_options.clickBlock && this.toString().match(/\.gif|\.jpg|\.jpeg|\.png/i)) e.stop();
```

Changing 'options' to '_options', small typo.

**Comment by iaian7** [comment]
Unfortunately, this does not fix the issue, as the _options object is not fully defined until after this segment of code (only once the links are parsed is the options object populated). As an intermediate solution, the option has simply been removed. I hope someone will still be able to step up and help out with creating a new backbone for the script using modern methods, should be a little cleaner!
